Laboratorium 3 - App/Models/Contact.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Laboratorium_3___App.Models
{
    public class Contact
    {
        [HiddenInput]
        public int Id {get ; set;}
        [Required(ErrorMessage ="Musisz wpisać imię!")]
        [StringLength(maximumLength: 100, ErrorMessage ="Zbyt długie imię, maksymalnie 100 znaków!")]
        public string Name { get; set;}
        [Required(ErrorMessage ="Musisz podać email!")]
        [EmailAddress(ErrorMessage ="Niepoprawny adres email, brak znaku @")]
        public string Email { get; set;}
        [Phone(ErrorMessage ="Niepoprawny numer telefonu!")]
        public string Phone { get; set;}
        public DateTime Birth { get; set; }
        [Display(Name = "Priorytet")]
        public Priority Priority { get; set; }
    }
}

Laboratorium 3 - App/Models/EnumExtensions.cs
using System.ComponentModel.DataAnnotations;
using System.Reflection;

namespace Laboratorium_3___App.Models
{
    static public class EnumExtensions
    {
        public static string GetDisplayName(this Enum enumValue)
        {
            return enumValue.GetType()
                            .GetMember(enumValue.ToString())
                            .First()
                            .GetCustomAttribute<DisplayAttribute>()
                            .GetName();
        }
    }
}

Laboratorium 3 - App/Models/ErrorViewModel.cs
namespace Laboratorium_3___App.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Laboratorium 3 - App/Models/IBookService.cs
namespace Laboratorium_3___App.Models
{
    public interface IContactService
    {
        int Add(Contact book);
        void Delete(int id);
        void Update(Contact book);
        List<Contact> FindAll();
        Contact? FindById(int id);
    }
}

Laboratorium 3 - App/Models/MemoryContactService.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace Laboratorium_3___App.Models
{
    public class MemoryContactService : IContactService
    {
        private Dictionary<int, Contact> _items = new Dictionary<int, Contact>();
        public int Add(Contact item)
        {
            int id = _items.Keys.Count != 0 ? _items.Keys.Max() : 0;
            item.Id = id + 1;
            _items.Add(item.Id, item);
            return item.Id;
        }

        public void Delete(int id)
        {
            _items.Remove(id);
        }

        public List<Contact> FindAll()
        {
            return _items.Values.ToList();
        }

        public Contact? FindById(int id)
        {
            return _items[id];
        }

        public void Update(Contact item)
        {
            _items[item.Id] = item;
        }
    }   
}

Laboratorium 3 - App/Models/Priority.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace Laboratorium_3___App.Models
{
    public enum Priority
    {
        [Display(Name = "Niski")] Low = 1,
        [Display(Name = "Normalny")] Normal = 2,
        [Display(Name = "Wysoki")] High = 3,
        [Display(Name = "Pilny")] Urgent = 4
    }
}

Laboratorium 3 - App/Models/Reservation.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Laboratorium_3___App.Models
{
    public class Reservation
    {
        [HiddenInput]
        public int Id { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Musisz podać datę!")]
        public DateTime? Data { get; set; }

        [Required(ErrorMessage = "Musisz wpisać miasto!")]
        public string Miasto { get; set; }

        [Required(ErrorMessage = "Musisz wpisać adres!")]
        public string Adres { get; set; }

        [Required(ErrorMessage = "Musisz wpisać pokój!")]
        public string Pokoj { get; set; }

        [Required(ErrorMessage = "Musisz wpisać właściciela!")]
        public string Wlasciciel { get; set; }

        [Required(ErrorMessage = "Musisz wpisać cenę!")]
        public decimal? Cena { get; set; }
    }
}

Laboratorium 3 - App/Controllers/ContactController.cs
using Laboratorium_3___App.Models;
using Microsoft.AspNetCore.Mvc;

namespace Laboratorium_3___App.Controllers
{
    public class ContactController : Controller
    {
        static readonly Dictionary<int, Contact> _contacts = new Dictionary<int, Contact>();
        static int index = 1;
        private IContactService _contactService;

        public ContactController(IContactService contactService)
        {
            _contactService = contactService;
        }
        public IActionResult Index()
        {
            return View(_contactService.FindAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Contact model)
        {
            if (ModelState.IsValid)
            {
                _contactService.Add(model);
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }
        [HttpGet]
        public IActionResult Update(int id) 
        {
            return View("Update", _contacts[id]);
        }
        [HttpPost]
        public IActionResult Update(Contact model) 
        {
            if (ModelState.IsValid)
            {
                _contacts[model.Id] = model;
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            return View(_contacts[id]);
        }
        [HttpGet]
        public IActionResult Delete(int id) 
        {
            return View(_contacts[id]);
        }
    }
}

Laboratorium 3 - App/Controllers/HomeController.cs
using Laboratorium_3___App.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Laboratorium_3___App.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Laboratorium 3 - App/Controllers/ReservationController.cs
using Laboratorium_3___App.Models;
using Microsoft.AspNetCore.Mvc;

namespace Laboratorium_3___App.Controllers
{
    public class ReservationController : Controller
    {
        static readonly Dictionary<int, Reservation> _reservations = new Dictionary<int, Reservation>();
        static int index = 1;
        public IActionResult Index()
        {
            return View(_reservations);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Reservation model)
        {
            if (ModelState.IsValid)
            {
                model.Id = index++;
                _reservations[model.Id] = model;
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            if (_reservations.TryGetValue(id, out var reservation))
            {
                return View(reservation);
            }
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(_reservations[id]);
        }
        [HttpPost]
        public IActionResult Delete(Reservation model)
        {   
            _reservations.Remove(model.Id);
            
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            return View("Update", _reservations[id]);
        }
        [HttpPost]
        public IActionResult Update(Reservation model)
        {
            if (ModelState.IsValid)
            {
                _reservations[model.Id] = model;
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

Laboratorium 3 - App/Views/Contact/Create.cshtml
@model Contact
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Dodawanie kontaktu</h1>
<form asp-controller="Contact" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="Name">Imię</label>
        <input class="form-control" asp-for="Name"/>
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Email">Email</label>
        <input class="form-control" asp-for="Email" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Phone">Telefon</label>
        <input class="form-control" asp-for="Phone" />
        <span asp-validation-for="Phone" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Birth">Data urodzenia</label>
        <input class="form-control" asp-for="Birth" />
        <span asp-validation-for="Birth" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <button class="btn btn-primary" type="submit">Utwórz</button>
    </div>
    <div>
        <label asp-for="Priority">Kategoria</label>
        <div>
            <span asp-validation-for="Priority" class="text-danger"></span>
        </div>
        <select class="form-control" asp-for="Priority" asp-items="@Html.GetEnumSelectList<Priority>()"></select>
    </div>
</form>

Laboratorium 3 - App/Views/Contact/Delete.cshtml
@model Contact
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form asp-action="Delete" method="post">
    <input asp-for="Id"/>
    <p>Czy na pewno usunąć?</p>
    <button type="submit">Tak</button>
    <a asp-controler="Contact" asp-action="Index">Nie</a>
</form>

Laboratorium 3 - App/Views/Contact/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Laboratorium 3 - App/Views/Contact/Index.cshtml
@model List<Contact>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Lista kontaktów</h1>
<div>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Priority)
            </th>
            <th>
                Akcje
            </th>
        </tr>
        @foreach(var item in @Model)
        {
            <tr>
                <td>
                    @item.Name
                </td>
                <td>
                    @item.Email
                </td>
                <td>
                    @item.Priority.GetDisplayName()
                </td>
                <td>
                    <a class="btn btn-outline-primary" asp-controller="Contact" asp-action="Update" asp-route-id="@item.Id">Edycja</a>
                    <a class="btn btn-outline-info" asp-controller="Contact" asp-action="Details" asp-route-id="@item.Id">Szczgóły</a>
                    <a class="btn btn-outline-danger" asp-controller="Contact" asp-action="Delete" asp-route-id="@item.Id">Usuń</a>
                </td>

            </tr>
        }
    </table>
</div>

Laboratorium 3 - App/Views/Contact/Update.cshtml
@model Contact
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Edycja kontaktu</h1>
<form asp-controller="Contact" asp-action="update" method="post">
    <div class="mb-3">
        <label asp-for="Name">Imię</label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Email">Email</label>
        <input class="form-control" asp-for="Email" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Phone">Telefon</label>
        <input class="form-control" asp-for="Phone" />
        <span asp-validation-for="Phone" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Birth">Data urodzenia</label>
        <input class="form-control" asp-for="Birth" />
        <span asp-validation-for="Birth" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <button class="btn btn-primary" type="submit">Zapisz</button>
    </div>
</form>

Laboratorium 3 - App/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Laboratorium 3 - App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Laboratorium_3_App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Laboratorium_3___App.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Laboratorium_3___App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Create">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="Create">Rezerwacja</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Laboratorium_3___App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>